version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: v1.0.2
  ignore:
  - dependency-name: org.apache.maven:maven-plugin-api
    versions:
    - 3.6.3
